---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: react-front
  name: react-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: react-front
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.name: react-front
        tier: frontend
    spec:
      containers:
      - image: front:devspace-intro
        imagePullPolicy: Always
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
        name: react-front
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always