---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: todo-list
  name: todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: todo-list
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.name: todo-list
        tier: frontend
    spec:
      containers:
      - image: back:devspace-intro
        imagePullPolicy: Always
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
        name: todo-list
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always